name: deploy_release
on:
  push:
    branches:
      - 'sbx'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to publish
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v0.0.4
      - name: Publish release
        uses: eloquent/github-release-action@v2

