name: dev_ecr_build
on:
  push:
    tags:
      - 'dev-v*' # Push events to matching dev-v*, i.e. dev-v1.0, dev-v20.15.10

jobs:
  deploy:
    name: Deploy ECR Registry
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Runtime vars
        run: |
          echo "SHA = ${{ github.sha }}"
          echo "github event ref = ${{ github.event.ref }}"
          echo "github ref = ${{ github.ref }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_dev }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_dev }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set vars to dev
        if: |
          startsWith(github.event.ref, 'refs/tags/dev-v') ||
          endsWith(github.ref, '/dev')
        run: |
          echo "AWS_ACCNT=770750324254" >> $GITHUB_ENV
          echo "ECR_REGISTRY=$AWS_ACCNT.dkr.ecr.us-east-1.amazonaws.com" >> $GITHUB_ENV
          echo "ECR_SHA_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "ECR_WEB_REPOSITORY=dw-web-image-repo" >> $GITHUB_ENV
          this_version=$(echo "${{ github.ref }}" | cut -f3 -d'/')
          echo "RELEASE_VERSION=$this_version" >> $GITHUB_ENV

      - name: ECR dw-web-image-repo 
        if: |
          startsWith(github.event.ref, 'refs/tags/dev-v') ||
          endsWith(github.ref, '/staging')
        id: build-image
        env:
          DOCKER_BUILDKIT: 1
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dw-web-image-repo
        run: |
          docker build \
                --file ./Dockerfile \
                --tag $ECR_REGISTRY/$ECR_API_REPOSITORY:$ECR_SHA_TAG \
                --tag $ECR_REGISTRY/$ECR_API_REPOSITORY:$RELEASE_VERSION \
                --tag $ECR_REGISTRY/$ECR_API_REPOSITORY:latest  \
                .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags



