name: dev_ecr_build
on:
  push:
    branches:
      - 'dev'

jobs:
  deploy:
    name: Deploy ECR Registry in Dev
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Get runtime vars
        run: |
          echo "SHA = ${{ github.sha }}"
          echo "github event ref = ${{ github.event.ref }}"
          echo "github ref = ${{ github.ref }}"

      - name: Checkout
        uses: actions/checkout@v2


      - name: Tag with Vinnie
        run: |
          # Setup git user
          git config --global user.email "watson.ops@gmail.com"
          git config --global user.name "Watson Ops"
          # Install vinnie
          pip install vinnie
          vinnie --prefix=dev-v version



