name: CI 

on:
  push:
    branches:
      - 'sbx'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v10
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v20
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/watsonops/simplewhale:latest

