name: pipeline_push
on:
  push:
    branches: dev
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: docker ghcr login push
        env:
          GHCR_USER: ${{secrets.GHCR_USER}}
          GHCR_TOKEN: ${{secrets.GHCR_TOKEN}}
        run: |
            docker login ghcr.io -u $GHCR_USER -p $GHCR_TOKEN
      -
        name: dockeer list
        run: | 
          docker image ls
          docker pull ghcr.io/watsonops/hello-world:latest
          docker inspect ghcr.io/watsonops/hello-world:latest

