name: GitHub Actions 
on: [push]
jobs:
  WatsonOps-Push:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ secrets.PIPELINE_PAT }} | docker login ghcr.io -u Pipeline_PAT --password-stdin
          docker image ls

      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

