name: release-buildx
on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      -
        name: docker ghcr login push
        env:
          GHCR_USER: ${{secrets.GHCR_USER}}
          GHCR_TOKEN: ${{secrets.GHCR_TOKEN}}
        run: |
            docker login ghcr.io -u $GHCR_USER -p $GHCR_TOKEN
