name: GitHub Actions 
on: [push]
jobs:
  WatsonOps-Push:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u Pipeline_PAT --password-stdin
