name: stage_ecr
on:
  push:
    branches:
      - staging
      - build-artifacts-update
jobs:
  deploy:
    name: Deploy ECR Registry
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials - Stage
        if: endsWith(github.ref, '/staging')
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set env to staging
        if: endsWith(github.ref, '/staging')
        run: |
          echo "ECR_REGISTRY=786081340798.dkr.ecr.us-east-1.amazonaws.com" >> $GITHUB_ENV
          echo "ECR_SHA_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "ECR_WEB_REPOSITORY=temp-web-repo" >> $GITHUB_ENV
          echo "ECR_API_REPOSITORY=temp-api-repo" >> $GITHUB_ENV

      - name: temp-web-repo ECR
        if: endsWith(github.ref, '/staging')
        env:
          DOCKER_BUILDKIT: 1
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: temp-web-repo
        run: |
          docker pull nicolaka/netshoot
          docker tag nicolaka/netshoot $ECR_REGISTRY/$ECR_WEB_REPOSITORY:$ECR_SHA_TAG
          docker push $ECR_REGISTRY/$ECR_WEB_REPOSITORY:$ECR_SHA_TAG


      - name: temp-api-repo ECR
        if: endsWith(github.ref, '/staging')
        id: build-image
        env:
          DOCKER_BUILDKIT: 1
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: temp-api-repo
        run: |
          docker build \
                --file ./Dockerfile \
                --tag $ECR_REGISTRY/$ECR_API_REPOSITORY:$ECR_SHA_TAG \
                --tag $ECR_REGISTRY/$ECR_API_REPOSITORY:stage  \
                --tag $ECR_REGISTRY/$ECR_API_REPOSITORY:latest  \
                .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

      - name: Test en vars
        run: |
          whoami
          hostname
          date


